# Generated by Django 5.2.8 on 2025-12-15 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_make_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.contributortype', verbose_name='Contributor Type'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contribution',
            field=models.TextField(blank=True, help_text='Only displayed for Major Contributors', null=True),
        ),
    ]
