# Generated by Django 5.2.8 on 2025-12-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_alter_contributor_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='hidden',
            field=models.BooleanField(default=True, help_text='Hide your contributor profile from /community/contributors/[username]/', verbose_name='Hide public profile'),
        ),
    ]
